gethostip_0001:
	g++ gethostip_0001.cpp -o gethostip_0001 
gethostip_0002:
	g++ gethostip_0002.cpp -o gethostip_0002
gethostname_0001:
	g++ gethostname_0001.cpp -o gethostname_0001
gethostname_0002:
	g++ gethostname_0002.cpp -o gethostname_0002
.PHONY:clean
clean:
	rm -rf gethostip_0001 && rm -rf gethostip_0002 
