LongestSubstringWithoutRepeatingCharacters:
	g++ -g LongestSubstringWithoutRepeatingCharacters.cpp -o LongestSubstringWithoutRepeatingCharacters -std=c++11
clean:
	rm -rf LongestSubstringWithoutRepeatingCharacters
