LongestSubstringWithoutRepeatingCharacters:
	g++ -g LongestSubstringWithoutRepeatingCharacters.cpp -o LongestSubstringWithoutRepeatingCharacters -std=c++11
java:
	javac LongestSubstringWithoutRepeatingCharacters.java 
clean:
	rm -rf LongestSubstringWithoutRepeatingCharacters
