VerifyPreorderSequenceinBinarySearchTree:
	g++ -g VerifyPreorderSequenceinBinarySearchTree.cpp -o VerifyPreorderSequenceinBinarySearchTree -std=c++11
clean:
	rm -rf VerifyPreorderSequenceinBinarySearchTree
