PopulatingNextRightPointersinEachNodeII:
	g++ -g PopulatingNextRightPointersinEachNodeII.cpp -o PopulatingNextRightPointersinEachNodeII -std=c++11
clean:
	rm -rf PopulatingNextRightPointersinEachNodeII
