LowestCommonAncestorofaBinarySearchTree:
	g++ -g LowestCommonAncestorofaBinarySearchTree.cpp -o LowestCommonAncestorofaBinarySearchTree -std=c++11
clean:
	rm -rf LowestCommonAncestorofaBinarySearchTree
