ReadNCharactersGivenRead4IICallmultipletimes:
	g++ -g ReadNCharactersGivenRead4IICallmultipletimes.cpp -o ReadNCharactersGivenRead4IICallmultipletimes -std=c++11
clean:
	rm -rf ReadNCharactersGivenRead4IICallmultipletimes
